---
title: "Mini-Project 2"
author: "Your Name Here"
date: "October 31, 2017"
output: html_document
---

## Loading the data

This project is so interesting and relevant to my life!

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, include = FALSE, message = FALSE}
library(tidyverse)
```

```{r}
general_house <- house_elections %>%
  filter(general_votes != 0) #filter the house_elections data down to only the general elections
num_candidates <- general_house %>%
  arrange(state, district) %>%
  group_by(state, district) %>%
  summarize(N = n()) %>% #number of candidates in a district
  filter(N == 1) #1 candidate means there was only one candidate running in that district
# num_candidates looks at how many candidates ran unopposed in the house election. Since there are only eight who ran unoppoosed, and we are looking primarily at California, we decided that we did not need to make a change to the data based on that information. 
```

```{r}
house_candidates <- filter(candidates, cand_office == "H") #filter so that the candidates table only includes candidates running for the house of representatives
```


```{r}
small_house <- general_house %>%
  full_join(house_candidates, by = c("fec_id" = "cand_id")) %>%
  select(fec_id, state, district, incumbent, candidate_name, party, general_votes, ge_winner)
```

```{r}
small_house_contributions <- small_house %>%
  full_join(contributions, by = c("fec_id" = "cand_id")) %>%
  select(fec_id, state.x, district, incumbent, candidate_name, party, general_votes, ge_winner, transaction_type, transaction_amt)
```

```{r}
ca_house_contributions <- small_house_contributions %>%
  filter(state.x == "CA", transaction_type == "24A" | transaction_type == "24E")
#bring the house contributions table down to California, and only transactions of type 24A and 24E
```

```{r}
total_amount_tbl <- ca_house_contributions %>%
  group_by(candidate_name, transaction_type) %>%
  summarize(total_amount = sum(transaction_amt))
```

```{r}
small_ca_contributions <- ca_house_contributions %>%
  full_join(total_amount_tbl, by = c("candidate_name" = "candidate_name")) %>%
  select(fec_id, state.x, district, incumbent, candidate_name, party, general_votes, ge_winner, transaction_type.y, total_amount)
```
